//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNETWebApi.Models.FormsGeneratorDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public System.Guid Id { get; set; }
        public System.Guid IdQuestion { get; set; }
        public string ChoiceText { get; set; }
        public int Order { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
