//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNETWebApi.Models.FormsGeneratorDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsAnswered
    {
        public System.Guid Id { get; set; }
        public System.Guid IdUser { get; set; }
        public System.Guid IdForm { get; set; }
        public bool Finished { get; set; }
        public System.DateTime AnswerDate { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual User User { get; set; }
    }
}
